id: P010773
initial_creation_type: ocr
source_metadata:
  id: bdr:W25144
  title: དུས་རབས་ཉེར་གཅིག་པའི་གངས་ཅན་པ་རྣམས་ལ་ཕུལ་བའི་སྙིང་གཏམ།
  author: ''
  volumes:
    d5a5e2683bd64086b51dd98dc090acdf:
      image_group_id: I1KG23322
      title: ''
      volume_number: 1
      total_pages: 122
