id: I11A11B8A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:59:55+00:00'
last_modified: '2022-06-08T17:25:26.884038+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25144
  title: དུས་རབས་ཉེར་གཅིག་པའི་གངས་ཅན་པ་རྣམས་ལ་ཕུལ་བའི་སྙིང་གཏམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    88BF:
      image_group_id: I1KG23322
      title: ''
      total_pages: 122
      order: 1
      base_file: 88BF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
